const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
const fareRoutes = require('./routes/fareRoutes')
const app = express()
app.use(helmet())
app.use(cors({ origin: ['http://localhost:5173', 'http://localhost:3000'], credentials: true }))
app.use(express.json())
app.get('/health', (req, res) => res.json({ service: 'fare-service', status: 'ok' }))
app.use('/fare', fareRoutes)
app.use((req, res) => res.status(404).json({ error: 'Route not found' }))
module.exports = app
